version: 2.1

# circle ci orb's doc
# https://circleci.com/developer/orbs?filterBy=popular
orbs:
  # slack: circleci/slack@4.12
  aws-cli: circleci/aws-cli@3.2
  # aws-s3: circleci/aws-s3@3.1
  # aws-cli: circleci/aws-cli@1.4.1

workflows:
  frontend_deploy:
    jobs:
      - prod_frontend_deploy:
          name: "prod_frontend_site"
          app: "site"
          deploy_version: "202305191456"
          # context:
          #   - slack-secret-key
          filters:
            branches:
              only: main

jobs:
  prod_frontend_deploy:
    docker:
      - image: cimg/node:18.16.0-browsers
    parameters:
      app:
        type: string
      deploy_version:
        type: string
    environment:
      BUILD_PATH: dist
      BUCKET_NAME: vue3.wico.dev
      BUCKET_REGION: "us-west-1"
      AWS_DEFAULT_REGION: "us-west-1"
      CACHE_CONTROL: "max-age=5"
      # BUCKET_REGION: ap-northeast-1
      # AWS_DEFAULT_REGION: "ap-northeast-1"
      # SLACK_CHANNEL: "C05F95CDQCS"

    steps:
      # - slack/notify:
      #     channel: $SLACK_CHANNEL
      #     custom: |
      #         {
      #           "blocks": [
      #             {
      #               "type": "section",
      #               "fields": [
      #                 {
      #                   "type": "plain_text",
      #                   "text": "$CIRCLE_JOB - Building",
      #                   "emoji": true
      #                 }
      #               ]
      #             }
      #           ]
      #         }
      #     event: always

      - checkout

      - aws-cli/setup:
          profile-name: default

      - restore_cache:
          name: Restore Cache
          keys:
            - npm-packages-<<parameters.deploy_version>>-{{ .Branch }}-<<parameters.app>>-{{ checksum "package-lock.json" }}
            - npm-packages-<<parameters.deploy_version>>-{{ .Branch }}-<<parameters.app>>- # used if checksum fail

      - run:
          name: npm install
          command: npm clean-install

      # save packages as cache
      - save_cache:
          key: npm-packages-<<parameters.deploy_version>>-{{ .Branch }}-<<parameters.app>>-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Build <<parameters.app>>
          command: |
            npm run build || exit 1

      # - run:
      #     name: Debug info <<parameters.app>>
      #     command: |
      #       pwd
      #       ls -la

      - run:
          name: Deploy Build files to S3
          # working_directory: ./<<parameters.app>>
          command: |
            aws s3 cp --exclude "index.html" --region "${BUCKET_REGION}" --acl "public-read" --cache-control "${CACHE_CONTROL}" --recursive "${BUILD_PATH}/" "s3://${BUCKET_NAME}/"
            aws s3 cp --region "${BUCKET_REGION}" --acl "public-read" --cache-control "max-age=0" "${BUILD_PATH}/index.html" "s3://${BUCKET_NAME}/index.html"


      # - slack/notify:
      #       event: pass
      #       channel: $SLACK_CHANNEL
      #       template: basic_success_1

      # - slack/notify:
      #       event: fail
      #       channel: $SLACK_CHANNEL
      #       template: basic_fail_1

