version: 2.1
orbs:
  # circle ci orb's doc
  # https://circleci.com/developer/orbs?filterBy=popular&query=&page=1&pageSize=15
  aws-cli: circleci/aws-cli@3.1

workflows:
  frontend_deploy:
    jobs:
      - prod_deploy:
          name: "prod_deploy_site"
          app: "site"
          deploy_version: "202304181345"
          filters:
            branches:
              only: main

jobs:
  prod_deploy:
    parameters:
      app:
        type: string
      deploy_version:
        type: string
    docker:
      - image: cimg/node:18.16.0-browsers
    environment:
      BUILD_PATH: dist
      BUCKET_NAME: build-prod.wico.dev
      BUCKET_REGION: ap-northeast-1
      CACHE_CONTROL: "max-age=0"
      AWS_DEFAULT_REGION: "ap-northeast-1"

    steps:
      - checkout
      - run:
          name: Setting up project
          working_directory: ./
          command: |
            npm install

      - run:
          name: Build <<parameters.app>>
          working_directory: ./
          command: |
            npm run build || exit 1

      - run:
          name: Deploy Build files to S3
          working_directory: ./<<parameters.app>>
          command: |
            aws s3 cp --exclude "index.html" --region "${BUCKET_REGION}" --acl "public-read" --cache-control "${CACHE_CONTROL}" --recursive "${BUILD_PATH}/" "s3://${BUCKET_NAME}/"
            aws s3 cp --region "${BUCKET_REGION}" --acl "public-read" --cache-control "max-age=0" "${BUILD_PATH}/index.html" "s3://${BUCKET_NAME}/index.html"
